#
# sqlite3 Makefile
#

CC      = gcc
AR	    = ar
CFLAGS  = -O2 -fPIC -Wall -ansi -pedantic

SHLD = ${CC} ${CFLAGS}
LDSHFLAGS =
LDFLAGS =

RM      = cmd /c del /f


COMPILE.c=$(CC) $(CFLAGS) -c
.c.o:
	$(COMPILE.c) -o $@ $<


SRCS = time64.c

OBJS = $(SRCS:.c=.o)


default:	libtime64.a

libtime64.a:	$(OBJS)
	$(AR) -rv libtime64.a $(OBJS)

clean:
	$(RM) $(OBJS)